# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: 'none' # will disable CI builds entirely

pool:
  vmImage: 'windows-2019'
    
variables:
  BuildConfiguration: release
  
steps:

- task: UseDotNet@2
  displayName: Install .NET 6 sdk
  inputs:
    packageType: sdk
    version: 6.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: DotNetCoreCLI@2
  displayName: Restore Nuget Packages
  inputs:
    command: restore
    projects: '**/WebApp.csproj'
